### ISSUE TITLE
matchUsing calls the function to check whether it returns a boolean but this is not obvious and causes confusion

### ISSUE THREAD

**Issue by wallaceturner** [testpossessed/jsSubstitute#1] opened 2017-05-30 05:44 UTC
if you add a simple matcher on an object this falls over in a non-intuitive way to the callee

`mySub.receivedWith(1, 2, substitute.arg.matchUsing(function(a){return a.field1 === 3;}));`

results in
>TypeError: Cannot read property 'field1' of undefined

Its not intuitive because to the callee it looks like the system under test is passing the object a null value in fact its your sanitizer running to check it returns a boolean.

Can you move this to a runtime check instead? 

`

**Comment by testpossessed** [comment] 2017-05-30 09:02
I am pretty sure it says in the docs that your matcher must check for undefined first.   This is because we actually validate the matcher returns a Boolean during registration by executing it.

So your matcher would need to be

function(a) { return a && a.field1 === 3);

Mike

**Comment by testpossessed** [comment] 2018-06-04 09:41
Closing this as it works as designed

**Closed by testpossessed** 2018-06-04 09:41 UTC
